const { SpringDroid } = require('./springDroid');
const filename = __dirname + '/input.txt';

describe('Spring Droid', () => {
  const program1 = `
  NOT D J
  `;
  const program2 = `
  AND D J
  `;

  test('program 1 jumps into a hole.', async () => {
    const springDroid = new SpringDroid(filename);
    await springDroid.loadSpringScript(program1);
    await springDroid.walk();

    expect(springDroid.result).toBe(10);
    expect(springDroid.lastMoments).toBe(`
Walking...


Didn't make it across:

.................
.................
@................
#####.###########

.................
.................
.@...............
#####.###########

.................
..@..............
.................
#####.###########

...@.............
.................
.................
#####.###########

.................
....@............
.................
#####.###########

.................
.................
.....@...........
#####.###########

.................
.................
.................
#####@###########

`);
  })
  test('program 2 walks into a hole.', async () => {
    const springDroid = new SpringDroid(filename);
    await springDroid.loadSpringScript(program2);
    await springDroid.walk();

    expect(springDroid.result).toBe(10);
    expect(springDroid.lastMoments).toBe(`
Walking...


Didn't make it across:

.................
.................
@................
#####.###########

.................
.................
.@...............
#####.###########

.................
.................
..@..............
#####.###########

.................
.................
...@.............
#####.###########

.................
.................
....@............
#####.###########

.................
.................
.................
#####@###########

`);
  })

  const example1 = `
  NOT A J
  NOT B T
  AND T J
  NOT C T
  AND T J
  AND D J
  `;
  test.skip('example 1 jumps if a three-tile-wide hole (with ground on the other side of the hole) is detected.', async () => {
    const springDroid = new SpringDroid(filename);
    await springDroid.loadSpringScript(example1);
    await springDroid.walk();

    // Unclear how to test this with the inputfile given.
    expect(springDroid.result).toBe(10);
    expect(springDroid.lastMoments).toBe(`
Walking...


Didn't make it across:

.................
.................
@................
#####.###########

.................
.................
.@...............
#####.###########

.................
.................
..@..............
#####.###########

.................
.................
...@.............
#####.###########

.................
.................
....@............
#####.###########

.................
.................
.................
#####@###########

`);
  });
  
})